### ISSUE TITLE
Consider putting package on pypi

### ISSUE THREAD

**Issue by lowks** [cmarzullo/saltscaffold#1]
Could you upload your package to pypi so that people can just `pip install` it ?

**Comment by cmarzullo** [comment]
Sure! Lemme look into that.

**Comment by cmarzullo** [comment]
Well it seems to be working. Setup travis-ci which I'd been meaning to do also.

https://pypi.python.org/pypi/Saltscaffold

The readme page is all messed up. Probably cause I'm using markdown instead of RST. I'll keep poking at it.

Would you test and see if it works for you?

**Comment by lowks** [comment]
Works Great! 
![screen shot 2016-10-16 at 7 44 13 am](https://cloud.githubusercontent.com/assets/517395/19414062/700ac6e2-9374-11e6-8150-4fee98821da8.png)

**Comment by lowks** [comment]
If you want you can create issues on your project on improvements. I can lend a hand :)

**Comment by cmarzullo** [comment]
glad it worked! As for what to do next, there's plenty of options. But I don't want to force too much onto someone. I'll create an issue to solicit ideas.
